### PR TITLE
Implement #1008

### LINKED ISSUE #1008: As a dev, I want to create template files for R6 classes [FR]
**Quick helper in the spirit of add_XXX**
Create R6 boilerplate in  a new file 

**Describe the solution you'd like**
`add_r6()` with same interface as `add_fct()` and `add_utils`

`R6` comes with shiny and is thus already a dependency for golem, so the feature does not need "real" additional dependencies. 

The overall usefulness though is difficult to asses for me, it would certainly be beneficial when creating R6 classes for exchanging data between modules.

### PR DESCRIPTION
**Pull request by ilyaZar**
This PR could be used to resolve #1008 . The last bullet of the commit message  is probably subject to change, also the name "class" could be altered.

The boilerplate is not minimal/empty, but one almost always uses a public interface when creating a R6 class so it may be fine if it is already there

Otherwise, works exactly the same as `add_fct()` and `add_utils()`.

### CODE REVIEW

**Comment by ColinFay** [comment]
Hey @ilyaZar 

Thanks for your work. I won't merge __for now__, I need to think about this a little bit but overall I think it's a great idea :)

**Comment by ilyaZar** [comment]
sure! thanks for taking time to have a look at this @ColinFay !

**Comment by VincentGuyader** [comment]
It's certain that when referring to a file, we can't use `pkg` and keep `path`. However, the meaning behind the `pkg` parameter isn't very clear to me. I would tend to think that it expects a character string that references a package name.

For example, this seems strange to me: `pkg = get_golem_wd()`.

Why not use `pkg_dir`, or simply `golem_wd` when referring to the project that contains the Golem, for instance?

In any case, the deprecation of the parameter will need to be managed, with a message for users (similar to what was done in `readr` for transitioning from `path` to `file`).

**Comment by ColinFay** [comment]
Thanks, cherry picked here https://github.com/ThinkR-open/golem/pull/1118

**Pull request closed without merging**
