### PR TITLE
Issue-330

### PR DESCRIPTION
**Pull request by novica**
I moved the `write_there` function form `add_module.R` to utils.R and created a similar file function that uses `write_there` in `add_r_files.R`. I am not sure if it makes complete sense.

### CODE REVIEW

**Comment by ColinFay** [comment]
Mmh, unfortunately this `write_there` function relies on elements that are inside the function it's called from, hence extracting it to somewhere else would prevent it from working correctly :/ 

For example, in module_template:

```
module_template <- function(name, path, export, ph_ui = " ", ph_server = " "){
  write_there <- function(...){
    write(..., file = path, append = TRUE)
  }
```

The path is the one passed from `module_template(path = )`, so having `write_there()` outside of it would fail.

**Comment by novica** [comment]
So, you are saying keep the function where it is?

**Comment by ColinFay** [comment]
Yes, I think unfortunately this function should stay where it is, as I think it wouldn't work if you're putting it somewhere else. 

But I might be wrong here, have you tried using it that way? 

Thanks, 
C.

**Comment by novica** [comment]
With the function moved I am getting an error `'...' used in an incorrect context`.

**Pull request closed without merging**
