### PR TITLE
Create a _disable_autoload.R file, removed the RProfile options

### PR DESCRIPTION
**Pull request by ColinFay**

### CODE REVIEW

**Comment by ShixiangWang** [comment]
Hi @ColinFay, I use the feature but it still not works for shiny-server. Do you have any suggestion?

```
Warning in loadSupport(appDir, renv = sharedEnv, globalrenv = NULL) :
  Loading R/ subdirectory for Shiny application, but this directory appears to contain an R package. Sourcing files in R/ may cause unexpected behavior.
```

**Comment by ColinFay** [comment]
Hey @ShixiangWang, 

yeah it's a shiny bug, no worries, it doesn't prevent the app from working :) 

https://github.com/rstudio/shiny/issues/3355

**Comment by ShixiangWang** [comment]
@ColinFay Thank you :). I thought it loaded the R directory and may cause some problems.

By the way, can I ask a question about shiny-server? When I put an app to the shiny-server, I found info by `cat()` cannot be accessed in log file. I checked message(), cat() and print(), only info from message() can be found. Do you know how to config to put the cat info to log file?

```
  # Your application server logic
  cat("a test message from cat")
  print("a test message from print")
  message("a test message from message")
  # Settings --------------------
```

log:

```
# cat /var/log/shiny-server/coco-shiny-20221112-20*
su: ignoring --preserve-environment, it's mutually exclusive with --login
Warning in loadSupport(appDir, renv = sharedEnv, globalrenv = NULL) :
  Loading R/ subdirectory for Shiny application, but this directory appears to contain an R package. Sourcing files in R/ may cause unexpected behavior.
ℹ Loading coco

Listening on http://127.0.0.1:33201
a test message from message
```

**Comment by ShixiangWang** [comment]
I found passing `file = stderr()` to `cat()` can get the log.

**Pull request merged**
