### PR TITLE
Fix Add git last 01 start

### LINKED ISSUE #1093: Move `use_git()` to bottom to commit all at once in `dev/01_start.R` [FR]
**Is your feature request related to a problem?**
When starting a fresh golem I tend to immediately run `01_start.R` just to set up __*everything*__ and do not bother anymore. 

I also add  a `git`-workflow every time and can imagine that for many this became the start up workflow when starting a new shiny golem app.

However, because the `use_git()` call does not appear in the end I will have to commit twice:

1. doing the default "initial commit" as per the `use_git()` call in `dev/01_start.R` AND
2. when I execute the last lines (which I have to do manually again because the `use_git()` call restarts RStudio which is a bit annoying too) and __*again re-commit*__ the `test/`, `R/golem_utils_server.R` and `R/golem_utils_ui.R` etc. files:

re-commit

**Describe the solution you'd like**
It would be somewhat nicer (in my opinion) if sourcing the `dev/01_start.R` file would end with an initial commit and nothing else to do to be able to move e.g. `dev/02_dev.R` or somewhere else directly (without an additional re-commit step).

So ideally something like that:

Screenshot from 2023-08-10 15-01-36

**Additional context**
Can be changed by moving `git`-calls to the bottom #1094

### PR DESCRIPTION
**Pull request by ilyaZar**
Fix #1093 

Uses the `git`-calls at the bottom of `dev/01_start.R` and allows to move on to e.g. `dev/02_dev.R` in a clean state (everything comited to the initial commit without the need for a follow up commit or `git commit --amend`

### CODE REVIEW

**Comment by ColinFay** [comment]
Hey @ilyaZar, 

Sorry for the long time without an answer :) 

That does sound like a reasonable feature. 

That being said, it would be easier if you could do "bite-size" PR/commit — i.e. one commit == one feature/fix, instead of mixing feature / fix / typo correction :) 
I know it's a bit more complex but that makes handling git history and cherry picking easier — for example if I need to cherry pick the typo only or revert the feature without losing the typo correction :) 

I'll cherry pick this PR soon :)

**Comment by ilyaZar** [comment]
Hey @ColinFay , thanks for doing the work of merging ! 

Sure, will follow a more bite-sized commits style !

Let me know if you'd like me to tweak something in this current PR (just split one into two commits: one updates `NEWS` the other is for the actual PR). Or in any of the other PRs as I have not always been consistent there too..

Cheers !

**Comment by ColinFay** [comment]
I'll try to do some git wizardry to split this, that should be ok :) 

Will let you know

**Comment by ColinFay** [comment]
Cherry picked in #1111 and #1110

**Pull request closed without merging**
